version: 0.2

phases:
  pre_build:
    commands:
      - export NODE_OPTIONS=--max_old_space_size=4096
      - npm i -g yarn
      - yarn cache clean
      - yarn install 
      
  build:
    commands:
      - yarn build
artifacts:
  files:
    - "**/*"
 
  discard-paths: no
 
  base-directory: dist
